# Generated by Django 3.2.5 on 2021-07-27 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('Product_Model_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('Product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.categorymodel')),
            ],
        ),
    ]
